#!/opt/homebrew/bin/bash

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ===== Tiling setting =========================

yabai -m config \
	layout bsp \
	\
	window_placement second_child \
	\
	top_padding 10 \
	bottom_padding 10 \
	left_padding 10 \
	right_padding 10 \
	window_gap 15 \
	\
	auto_balance on \
	\
	split_ratio 0.5 \
	\
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	\
	focus_follows_mouse autoraise \
	mouse_follows_focus on \
	\
	window_topmost off \
	window_shadow on \
	\
	window_opacity off \
	active_window_opacity 1.0 \
	normal_window_opacity 1.0 \
	\
	window_border off \
	window_border_blur off \
	window_border_radius -1 \
	window_border_width 1 \
	active_window_border_color "0xffffffff" \
	normal_window_border_color "0x00ffffff" \
	\
	window_origin_display default \
	\
	window_animation_duration 0.3 \
	\
	external_bar all:0:0

# ===== Spaces =================================

yabai -m space 1 --label main
yabai -m space 2 --label action-1
yabai -m space 3 --label action-2
yabai -m space 4 --label messages
yabai -m space 5 --label mail

# ===== Rules ==================================

yabai -m rule --add label="Arc" app="^Arc$" title="^(Account)$" manage=off
yabai -m rule --add label="FaceTime" app="FaceTime" title=".*" manage=off
yabai -m rule --add label="JetBrains Toolbox" app="JetBrains Toolbox" title=".*" manage=off
yabai -m rule --add label="Microsoft Teams Notification" app="Microsoft Teams" title="Microsoft Teams Notification" manage=off mouse_follows_focus=off
yabai -m rule --add label="Raycast Settings" app="Raycast" title=".*" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off sticky=on

yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Avira" app="^Avira*" manage=off
yabai -m rule --add label="Bartender" app="^Bartender 4$" manage=off sticky=on
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off sticky=on
yabai -m rule --add label="Cryptomator" app="^Cryptomator" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Ivanti" app="^Ivanti*$" manage=off
yabai -m rule --add label="Maccy" app="^Maccy$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Stream" app="^Steam$" manage=off
yabai -m rule --add label="SwiftBar" app="^SwiftBar$" manage=off

yabai -m rule --add label="Messages" app="Messages" space=messages
yabai -m rule --add label="WhatsApp" app="WhatsApp" space=messages

yabai -m rule --add label="Thunderbird" app="Thunderbird" space=mail

yabai -m rule --add label="Android Studio" app="^Android Studio" manage=off title="^(Android Device Manager)$"
yabai -m rule --add label="Arc" app="^Arc$" manage=off title="^(Account|General|Shortcuts|Little Arc|Previews|Updates|Archive|Site Settings|Advanced)$"
yabai -m rule --add label="Finder" app="^Finder$" manage=off title="(Co(py|nnect)|Move|Info|Settings)"
yabai -m rule --add label="Rider" app="^JetBrains Rider$" manage=off title="^(Settings|Rename)$"
yabai -m rule --add label="Safari" app="^Safari$" manage=off title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$"
yabai -m rule --add label="Visual Studio" app="^Visual Studio$" manage=off title="^(Preferences|Find in Files)$"

yabai -m rule --add label="Arc System Dialog" app="^Arc$" subrole="AXSystemDialog" manage=off mouse_follows_focus=off border=off

# See: https://github.com/koekeishiya/yabai/issues/194#issuecomment-880106547
yabai -m rule --add app="^Android Studio" title!="(.*\[(.*)\].*)|(.*\(\:.*\).*)" manage=off
yabai -m rule --add app="^JetBrains Rider" title!="(.*\[(.*)\].*)|(.*\(\:.*\).*)" manage=off

# ===== Signals ================================

yabai -m signal --add event=window_created action="yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er '.\"can-resize\" == false and .\"is-floating\" == false' && yabai -m window $YABAI_WINDOW_ID --toggle float"

printf "yabai: configuration loaded...\\n"
