#!/opt/pkg/bin/bash

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ===== Tiling setting =========================

yabai -m config \
	layout bsp \
	window_placement second_child \
	top_padding 10 \
	bottom_padding 10 \
	left_padding 50 \
	right_padding 50 \
	window_gap 15 \
	auto_balance off \
	split_ratio 0.5 \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	window_origin_display default \
	window_animation_duration 0.2

#focus_follows_mouse autoraise \
#mouse_follows_focus on \

# ===== Spaces =================================

yabai -m space 2 --label web

yabai -m space 6 --label social

yabai -m config --space social left_padding 10
yabai -m config --space social right_padding 10

yabai -m space 7 --label mail

yabai -m config --space mail left_padding 210
yabai -m config --space mail right_padding 210

# ===== Rules ==================================

yabai -m rule --add label="FaceTime" app="FaceTime" title=".*" manage=off
yabai -m rule --add label="JetBrains Toolbox" app="JetBrains Toolbox" title=".*" manage=off
yabai -m rule --add label="Raycast Settings" app="Raycast" title=".*" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off sticky=on

yabai -m rule --add label="1Password" app="1Password" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="AirMessage" app="AirMessage" manage=off
yabai -m rule --add label="AltTab" app="AltTab" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Avira" app="Avira*" manage=off
yabai -m rule --add label="Bartender" app="Bartender" manage=off sticky=on
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off sticky=on
yabai -m rule --add label="Cryptomator" app="^Cryptomator" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Ivanti" app="Ivanti*" manage=off
yabai -m rule --add label="Maccy" app="^Maccy$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Stream" app="^Steam$" manage=off
yabai -m rule --add label="SwiftBar" app="^SwiftBar$" manage=off
yabai -m rule --add label="Xcodes" app="^Xcodes$" manage=off
yabai -m rule --add label="KeyboardCleanTool" app="^KeyboardCleanTool$" manage=off

yabai -m rule --add label="Messages" app="Messages" space=social
yabai -m rule --add label="Microsoft Teams" app="Microsoft Teams" space=social
yabai -m rule --add label="WhatsApp" app="WhatsApp" space=social

yabai -m rule --add label="Thunderbird" app="Thunderbird" space=mail

yabai -m rule --add label="Android Studio" app="^Android Studio" manage=off title="^(Preferences|Android Device Manager|Virtual Device Configuration|Add File to Git)$"
yabai -m rule --add label="Arc" app="^Arc$" manage=off title="^(Account|General|Shortcuts|Little Arc|Previews|Updates|Archive|Site Settings|Advanced)$"
yabai -m rule --add label="Calendar" app="^Calendar$" manage=off title="^$"
yabai -m rule --add label="Finder" app="^Finder$" manage=off title="(Co(py|nnect)|Move|Info|Settings)"
yabai -m rule --add label="Rider" app="^JetBrains Rider$" manage=off title="^(Settings|Rename)$"
yabai -m rule --add label="Safari" app="^Safari$" manage=off title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$"
yabai -m rule --add label="Visual Studio" app="^Visual Studio$" manage=off title="^(Preferences|Find in Files)$"

# See: https://github.com/koekeishiya/yabai/issues/194#issuecomment-880106547
# yabai -m rule --add app="^Android Studio" title!="(.*\[(.*)\].*)|(.*\(\:.*\).*)" manage=off
# yabai -m rule --add app="^JetBrains Rider" title!="(.*\[(.*)\].*)|(.*\(\:.*\).*)" manage=off

# ===== Signals ================================

# Seems to be creating issues with windows. Commented out for time being.
#yabai -m signal --add event=window_created action="yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er '.\"can-resize\" == false and .\"is-floating\" == false or \",\"' && yabai -m window $YABAI_WINDOW_ID --toggle float"

printf "yabai: configuration loaded...\\n"
